---
title: "TaskSets"
author: "Maria Eckstein"
date: "July 19, 2017"
output: html_document
---

# Preprocessing

```{r Set parameters load packages etc.}
library("ggplot2"); library("plyr"); library("lme4"); library("reshape2"); library("zoo")
theme_set(theme_bw())

# TDs

run_on = "simulations"  # can be "fitted_humans", "gen_rec", "humans", or "simulations"
gg_save = T
run_regression = F
exclude_participants = T
n_aliens = 4
n_seasons = 3
n_trials = data.frame(a = 13, b = 10, x = 7, d = 7)
n_blocks = data.frame(a =  3, b =  3, x = 2, d = 2)
subj_value_phase = "Refresher2"
wanted_columns = c("subjID", "trial_index", "phase", "TS", "season", "sad_alien", "sad_alien_name", "item_left", "item_right", "item_chosen", "item_left_name", "item_right_name", "item_chosen_name", "assess", "reward", "correct", "block.type", "block", "trial_type", "model_name", "rt", "Q_TS", "Q_action", "p_TS", "p_action", "LL")
parameter_names = c("alpha", "alpha_high", "beta", "beta_high", "epsilon", "forget", "forget_high", "create_TS_biased")
if (run_on == "humans") {
  data_dir = "C:/Users/maria/MEGAsync/Berkeley/TaskSets/Data/version3.1"
  patt = "1...csv"
  plot_dir = file.path(data_dir, "plots")
} else {
  data_dir = "C:/Users/maria/MEGAsync/Berkeley/TaskSets/AlienGenRec/"
  patt = "sim_....csv"  # "alien_..csv" -> subjID1-9, "alien_...csv" -> subjID10-99, "alien_....csv" -> subjID100-999
  plot_dir = file.path(data_dir, "plots")
}
feed_aliens_phases = c("1InitialLearning", "2CloudySeason", "Refresher2", "Refresher3")
colnames(n_trials) = paste0("X", feed_aliens_phases)
colnames(n_blocks) = paste0("X", feed_aliens_phases)
n_trials
n_blocks
if (!dir.exists(plot_dir)) {
  dir.create(plot_dir)
}
perf_criterion = 0.5  # participants who perform worse that that at the end of training (last 4 trials per alien) are excluded
```
```{r Read in all data}
filenames = list.files(data_dir, pattern = patt)
all_files = data.frame()

for (filename in filenames[1:10]) {
  subj_file = read.csv(file = file.path(data_dir, filename), header = T, na.strings = c("", "NA", "NaN", "-1"))
  
  if (run_on == "humans") {
    # Get subjID
    demos = gsub("[^A-Za-z0-9/]", "", as.character(subj_file$responses)[1])  # get rid of all funny characters
    subj_file$subjID = as.numeric(strsplit(strsplit(demos, "Q0")[[1]][2], "Q1")[[1]][1])
  }
  
  all_files = rbind(all_files, subj_file)
}
subj_file
all_files
summary(all_files)
```
```{r Human demographics}
if (run_on == "humans") {
  demo_data = subset(all_files, select = "responses", trial_index == 0)
}
# # Get demographics
# demos = gsub("[^A-Za-z0-9/]", "", as.character(demo_data$responses)[1])  # get rid of all funny characters
# Q0split = strsplit(strsplit(demos, "Q0")[[1]][2], "Q1")[[1]][1]
# Q1split = strsplit(strsplit(demos, "Q1")[[1]][2], "Q2")[[1]][1]
# Q1split = gsub("[^0-9/]", "", Q1split)  # remove non-numbers
# Q2split = strsplit(strsplit(demos, "Q2")[[1]][2], "Q3")[[1]][1]
# Q2split = gsub("[^0-9/]", "", Q2split)  # remove non-numbers
# Q3split = strsplit(demos, "Q3")[[1]][2]
# 
# # Subj ID & sex
# subjID = as.numeric(Q0split)
# demographics[demo_row, "subjID"] = subjID
# demographics[demo_row, "sex"] = Q3split
# 
# # Date of birth (year, month, day is all wrong!!! let Lucy fix it and then rewrite!)
# month = as.numeric(strsplit(Q1split, "/")[[1]][1])
# day = as.numeric(strsplit(Q1split, "/")[[1]][2])
# year = as.numeric(strsplit(Q1split, "/")[[1]][3])
# if (nchar(year) == 2) {
#   year = paste("19", year, sep = "")
# }
# demographics[demo_row, "dob"] = paste(year, month, day, sep = "-")
# 
# # Testing date
# month = as.numeric(strsplit(Q2split, "/")[[1]][1])
# day = as.numeric(strsplit(Q2split, "/")[[1]][2])
# year = as.numeric(strsplit(Q2split, "/")[[1]][3])
# if (nchar(year) == 2) {
#   year = paste("20", year, sep = "")
# }
# demographics[demo_row, "testing_date"] = paste(year, month, day, sep = "-")
# demo_row = demo_row + 1
# 
# subj_file$subjID = subjID
# subj_file = subset(subj_file, select = -c(responses, internal_node_id, view_history))
```
```{r Get human data into the right format}
if (run_on == "humans") {
  
  all_files = subset(all_files, trial_type %in% c("feed-aliens", "pick-aliens") & phase != "0Training")
  all_files$model_name = "human"
  all_files$reward[is.na(all_files$key)] = 0
  all_files$season = factor(gsub("_cloudy", "", all_files$season))
  all_files$TS = factor(all_files$TS)
  
  summary(all_files)
}
```
```{r Get simulated data into the right format}
if (run_on == "simulations") {
  all_files[all_files$learning_style %in% c("flat", "s-flat"), "alpha_high"] = 0
  all_files[all_files$learning_style %in% c("flat", "s-flat"), "beta_high"] = 0
  all_files[all_files$learning_style %in% c("flat", "s-flat"), "forget_high"] = 0
  all_files[all_files$learning_style == "hierarchical" & all_files$alpha == all_files$alpha_high, "alpha_high"] = 0
  all_files[all_files$learning_style == "hierarchical" & all_files$beta == all_files$beta_high, "beta_high"] = 0
  all_files[all_files$learning_style == "hierarchical" & all_files$forget == all_files$forget_high, "forget_high"] = 0
  # Rename TS-related columns
  colnames(all_files)[colnames(all_files) == "sID"] = "subjID"
  colnames(all_files)[colnames(all_files) == "TS"] = "selected_TS"
  colnames(all_files)[colnames(all_files) == "context"] = "TS"
  
  # Remove unwanted rows
  all_files = subset(all_files, phase != 0)
  
  # Add season and xyz_name columns
  all_files$item_chosen[all_files$phase != '3PickAliens'] = as.numeric(as.character(all_files$item_chosen[all_files$phase != '3PickAliens']))
  new_all_files = data.frame()
  for (subjIDi in unique(all_files$subjID)) {
    
    subj_rows = all_files$subjID == subjIDi
    subj_learning_style = all_files[subj_rows, "learning_style"][1]
    non0_parameters = parameter_names[all_files[subj_rows, parameter_names][1,] != 0]
    subj_model_parameters = paste(non0_parameters, collapse="_")[1]
    all_files[subj_rows, "model_name"] = paste0(subj_learning_style, "_", subj_model_parameters)
    
    subj_feedaliens_rows = (all_files$subjID == subjIDi) & (all_files$phase != "3PickAliens")
    subj_pickaliens_rows = (all_files$subjID == subjIDi) & (all_files$phase == "3PickAliens")
    subj_file_feed = all_files[subj_feedaliens_rows,]
    subj_file_pick = all_files[subj_pickaliens_rows,]
    
    TS_seasons = data.frame(TS = c(0, 1, 2, 4), season = c(sample(c("hot", "cold", "rainy")), "rainbow"))
    alien_ids_names = data.frame(sad_alien = 0:3, sad_alien_name = sample(paste0("alien", 0:3)))
    item_ids_names = data.frame(item = 0:2, item_name = sample(c("bed", "plant", "umbrella")))
    
    # Add season and xyz_name columns (feed-aliens phases)
    subj_file_feed = merge(subj_file_feed, TS_seasons, all.x = T)
    subj_file_feed = merge(subj_file_feed, alien_ids_names, all.x = T)
    for (item in c("item_left", "item_right", "item_chosen")) {
      subj_file_feed = merge(subj_file_feed, item_ids_names, by.x = item, by.y = "item", all.x = T)
      colnames(subj_file_feed)[colnames(subj_file_feed) == "item_name"] = paste0(item, "_name")
    }
    
    # Add xyz_name columns (pick-aliens phase)
    subj_file_pick_items = subset(subj_file_pick, assess == "item")
    subj_file_pick_aliens = subset(subj_file_pick, assess == "alien")
    subj_file_pick_seasons = subset(subj_file_pick, assess == "season")
    subj_file_pick_alienseasons = subset(subj_file_pick, assess == "alien-same-season")
    
    for (item in c("item_left", "item_right", "item_chosen")) {
      subj_file_pick_items = merge(subj_file_pick_items, item_ids_names, by.x = item, by.y = "item", all.x = T)
      colnames(subj_file_pick_items)[colnames(subj_file_pick_items) == "item_name"] = paste0(item, "_name")
    }
    
    for (item in c("item_left", "item_right", "item_chosen")) {
      subj_file_pick_aliens = merge(subj_file_pick_aliens, alien_ids_names, by.x = item, by.y = "sad_alien", all.x = T)
      colnames(subj_file_pick_aliens)[colnames(subj_file_pick_aliens) == "sad_alien_name"] = paste0(item, "_name")
    }
  
    for (item in c("item_left", "item_right", "item_chosen")) {
      subj_file_pick_seasons = merge(subj_file_pick_seasons, TS_seasons, by.x = item, by.y = "TS", all.x = T)
      colnames(subj_file_pick_seasons)[colnames(subj_file_pick_seasons) == "season"] = paste0(item, "_name")
    }
  
    for (item in c("item_left", "item_right", "item_chosen")) {
      subj_file_pick_alienseasons$TS_ = substr(subj_file_pick_alienseasons[,item], 2, 2)
      subj_file_pick_alienseasons$sad_alien_ = substr(subj_file_pick_alienseasons[,item], 5, 5)
  
      subj_file_pick_alienseasons = merge(subj_file_pick_alienseasons, TS_seasons, by.x = "TS_", by.y = "TS", all.x = T)
      colnames(subj_file_pick_alienseasons)[colnames(subj_file_pick_alienseasons) == "season"] = paste0(item, "_name_season")
      subj_file_pick_alienseasons = merge(subj_file_pick_alienseasons, alien_ids_names, by.x = "sad_alien_", by.y = "sad_alien", all.x = T)
      colnames(subj_file_pick_alienseasons)[colnames(subj_file_pick_alienseasons) == "sad_alien_name"] = paste0(item, "_name_alien")
  
      subj_file_pick_alienseasons[,paste0(item, "_name")] = paste0(subj_file_pick_alienseasons[,paste0(item, "_name_alien")], subj_file_pick_alienseasons[,paste0(item, "_name_season")])
      subj_file_pick_alienseasons$TS_ = subj_file_pick_alienseasons$sad_alien_ = subj_file_pick_alienseasons[,paste0(item, "_name_season")] = subj_file_pick_alienseasons[,paste0(item, "_name_alien")] = NULL
    }
    
    new_all_files = rbind(new_all_files,
                          subj_file_feed,
                          cbind(subj_file_pick_items, season = NA, sad_alien_name = NA),
                          cbind(subj_file_pick_aliens, season = NA, sad_alien_name = NA),
                          cbind(subj_file_pick_seasons, season = NA, sad_alien_name = NA),
                          cbind(subj_file_pick_alienseasons, season = NA, sad_alien_name = NA))
  }
  assertthat::assert_that(dim(new_all_files)[1] == dim(all_files)[1])
  all_files = new_all_files
}
```
```{r Get parameter_dat}
if (run_on %in% c("gen_rec", "simulations")) {
  parameter_dat = ddply(all_files, c("subjID", "model_name", parameter_names), summarize,
                       alpha = alpha[1],
                       beta = beta[1],
                       forget = forget[1])
  parameter_dat
} else {
  parameter_dat = data.frame(subjID = unique(all_files$subjID), model_name = "human")
  for (par_name in parameter_names) {
    parameter_dat[,par_name] = 999
  }
}
```
```{r For all_files form all sources: remove excess columns and rows}
# Add NAs for all other wanted_columns
for (wanted_column in wanted_columns) {
  if (! wanted_column %in% colnames(all_files)) {
    all_files[wanted_column] = NA
  }
}
all_files = subset(all_files, select = wanted_columns)

# Factors and other beautification
all_files$correct[all_files$phase == "3PickAliens"] = NA
all_files$correct = as.logical(all_files$correct)
all_files$trial_type = factor(all_files$trial_type)
all_files$model_name = factor(all_files$model_name)
all_files = all_files[order(all_files$subjID, all_files$trial_index, all_files$phase, all_files$sad_alien, all_files$TS),]
summary(all_files)
```
```{r Make sure all_files looks good}
correct_nrows = assertthat::are_equal(nrow(subj_file) * length(filenames), nrow(all_files))
if (!correct_nrows) {
  warning(paste("all_files does not have the expected number of rows. Expected: nrow(subj_file) * length(filenames) =", nrow(subj_file), "*", length(filenames), "=", nrow(subj_file) * length(filenames), "- Actual:", nrow(all_files)))
}

for (wanted_column in wanted_columns) {
  if (! wanted_column %in% colnames(all_files)) {
    stop(paste("The column", wanted_column, "is missing in all_files!"))
  }
}
```
```{r Add columns alien_trial and repetition}
old_allfiles_dim = dim(all_files)

# Create new columns
all_files$block = NA
all_files$alien_trial = NA
all_files$repetition = NA
  
for (subjIDi in unique(all_files$subjID)) {
  
  # Get data from one subject
  subj_phase_rows = all_files$subjID == subjIDi & all_files$phase != "3PickAliens"
  subj_file = all_files[subj_phase_rows,]
  
  # Create counters for seasons and alien_season combos
  block = 0
  season_counter = data.frame(hot = 0, cold = 0, rainy = 0, rainbow = 0)
  alien_season_counter = data.frame(hot = rep(0, n_aliens), cold = rep(0, n_aliens), rainy = rep(0, n_aliens), rainbow = rep(0, n_aliens))

  for (row in 1:nrow(subj_file)) {
    
    # Get current alien and season
    sad_alien = subj_file$sad_alien[row] + 1  # Python starts at 0, I start at 1
    season = as.character(subj_file$season[row])
    
    # Figure out whether season changed
    if (row == 1) {
      new_season = T
    } else {
      new_season = subj_file$season[row] != subj_file$season[row-1]
    }
    
    # Update season and season-alien counters
    if (new_season) {
      season_counter[season] = season_counter[season] + 1
      block = block + 1
    }
    alien_season_counter[sad_alien, season] = alien_season_counter[sad_alien, season] + 1
    
    # Update repetition and alien_trial in the subj_file
    subj_file$block[row] = block
    subj_file$repetition[row] = season_counter[season][[1]]
    subj_file$alien_trial[row] = alien_season_counter[sad_alien, season]
  }
  
  # Add subject data back into all_files
  all_files[subj_phase_rows,] = subj_file
}

all_files$block[all_files$block.type == "mixed"] = NA
summary(all_files)
subset(all_files, repetition > 30)
```
```{r Code factors as factors}
all_files$phase = factor(all_files$phase, levels = c("1InitialLearning", "2CloudySeason", "Refresher2", "3PickAliens", "Refresher3", "5RainbowSeason"))
all_files$subjID = as.numeric(as.character(all_files$subjID))
all_files$block.type = factor(all_files$block.type)
all_files$sad_alien = factor(all_files$sad_alien)
all_files$ACC = ifelse(as.character(all_files$correct) %in% c("true", "True", T), 1, 0)
```
```{r Verify that everything looks good}
assertthat::are_equal(old_allfiles_dim[1], dim(all_files)[1])

assertthat::are_equal(max(all_files$alien_trial, na.rm = T), sum(n_trials))
assertthat::are_equal(min(all_files$alien_trial, na.rm = T), 1)  # or 0?

assertthat::are_equal(max(all_files$repetition, na.rm = T), sum(n_blocks))
assertthat::are_equal(min(all_files$repetition, na.rm = T), 1)  # or 0?
```
```{r Show all_files and make test plots to check that everything looks good}
all_files
summary(all_files)

# Make sure that the dataset has legit responses for each phase
ggplot(all_files, aes(trial_index, item_chosen, color = phase)) +
  stat_summary(fun.data = mean_se, geom = "pointrange") +
  geom_point()

# Make sure that participants are rewarded according to a legit TS in a specific context ("rainiy")
ddply(subset(all_files, season == "rainy" & ACC == 1), .(subjID, TS, sad_alien, item_chosen), summarize,
      rew = mean(reward, na.rm = T))
```
```{r Exclude subjects who don't reach criterion in training block and plot performance and missed trials}
if (run_on == "humans") {
  subset(all_files, season == "training")
  perf_dat = ddply(subset(all_files, season == "training" & alien_trial %in% 7:10),
                   .(subjID), summarize,
                   ACC = mean(ACC, na.rm = T))
  gg_criterion_perf = ggplot(perf_dat, aes(factor(subjID), ACC)) +
    geom_point() +
    geom_hline(yintercept = perf_criterion, color = "red", linetype = "dotted")
  perf_dat$below_criterion = perf_dat$ACC < perf_criterion
  (chance_performers = subset(perf_dat, below_criterion == T))
  if (exclude_participants) {
    all_files = subset(all_files, !subjID %in% chance_performers$subjID)
  }
  
  missed_trials_dat = ddply(subset(all_files, !is.na(phase)), .(subjID, phase, block.type), summarize,
        n_missed_trials = sum(is.na(item_chosen_name)),
        perc_missed_trials = 100 * mean(is.na(item_chosen_name)),
        med_RTs = median(rt, na.rm = T))
  
  gg_missed_trials = ggplot(missed_trials_dat, aes(phase, perc_missed_trials, color = block.type, fill = block.type)) +
    stat_summary(fun.y = "mean", geom = "bar", position = position_dodge(width = 0.9), alpha = 0.8) +
    geom_point(position = "jitter") +
    stat_summary(fun.data = "mean_se", geom = "pointrange", position = position_dodge(width = 0.9), color = "black")
  gg_med_RTs = gg_missed_trials + aes(y = med_RTs / 1000)
  
  if (gg_save) {
    ggsave(file.path(plot_dir, "1gg_criterion_perf.png"), gg_criterion_perf, width = 6, height = 3)
    ggsave(file.path(plot_dir, "1gg_missed_trials.png"), gg_missed_trials, width = 6, height = 3)
    ggsave(file.path(plot_dir, "1gg_med_RTs.png"), gg_med_RTs, width = 6, height = 3)
  }
}
```

# Results

```{r Check if TS values and action values are correlated for the current TS and current action}
gg_Q_high_low = ggplot(all_files, aes(Q_TS, Q_action, color = subjID)) +
  geom_point() +
  facet_grid(model_name ~ .)
gg_p_high_low = gg_Q_high_low + aes(p_TS, p_action)

if (gg_save) {
  ggsave(file.path(plot_dir, "gg_Q_high_low.png"), gg_Q_high_low)
  ggsave(file.path(plot_dir, "gg_p_high_low.png"), gg_p_high_low)
}
```
```{r Plot overall learning}
# Plot learning curves (and RTs) overall
overall_learning_curves =
  ggplot(all_files, aes(trial_index, 100 * ACC, color = phase, group = phase, shape = factor(block.type))) +
  stat_summary(fun.data = mean_se, geom = "pointrange") +
  geom_hline(yintercept = 100/3, linetype = "dotted") +
  geom_hline(yintercept = 600/8, linetype = "dotted") +
  labs(x = "Trial", y = "% correct") +
  facet_grid(model_name ~ .)

overall_RTs = overall_learning_curves + aes(y = rt, color = phase) + labs(x = "Trial", y = "Response time (msec)")

if (gg_save) {
  ggsave(file.path(plot_dir, "1overall_learning_curves.png"), overall_learning_curves, width = 20, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "1overall_RTs.png"), overall_RTs, width = 25, height = 3)
}
```
```{r demographics}
# if (run_on != "simulations") {
#   demographics$age = with(demographics, as.Date(testing_date) - as.Date(dob))
#   nrow(demographics)  # number of participants
#   demographics = subset(demographics, subjID %in% unique(all_files$subjID))
#   nrow(demographics)  # number of participants after removing chance performaners
#   as.numeric(mean(demographics$age) / 365.242)  # mean age in years
#   as.numeric(sd(demographics$age) / 365.242)  # age sd
#   plot(as.numeric(demographics$age) / 365.242)  # plot to check
# }
```
```{r Create all_values_perf which contains TS and item values (subj and obj) and task performance}
# Function to summarize over items, aliens, TS, ..., to get average rewards for each
get_values_and_perf = function(feed_aliens_data, instance_names, instance_ids, assess_name) {
  
  value_dat = ddply(feed_aliens_data, c("subjID", "phase", "model_name", instance_names, instance_ids), summarize,
                    value_subj = mean(reward, na.rm = T),
                    av_ACC = mean(ACC, na.rm = T))
  
  if (length(instance_names) > 1) {
    value_dat$name = apply(value_dat[,instance_names], 1, paste, collapse = "")
    value_dat[,instance_names] = NULL
    value_dat$id = apply(value_dat[,instance_ids], 1, paste, collapse = "")
    value_dat[,instance_ids] = NULL
  } else {
    colnames(value_dat)[colnames(value_dat) == instance_names] = "name"
    colnames(value_dat)[colnames(value_dat) == instance_ids] = "id"
  }
  value_dat$assess = assess_name
  
  return(value_dat)
}

# True objective values for each season-alien pair
alien_TS_obj = expand.grid(sad_alien = 0:3, TS = 0:2)
alien_TS_obj$value_obj = c(6, 4, 5, 10,
                           2, 8, 7, 3,
                           7, 3, 3, 2)
alien_TS_obj$id = apply(alien_TS_obj[,c("sad_alien", "TS")], 1, paste, collapse = "")

# Put all the average rewards into one dataframe
dat = subset(all_files, phase %in% c("1InitialLearning", "Refresher2", "Refresher3") & !is.na(item_chosen) & block.type != "mixed")

alien_values = get_values_and_perf(dat, "sad_alien_name", "sad_alien", "alien")
alien_values$value_obj = 5

TS_values = get_values_and_perf(dat, "season", "TS", "season")
TS_values = merge(TS_values, data.frame(id = 0:2, value_obj = c(6.25, 5, 3.75)))

item_values = get_values_and_perf(dat, "item_chosen_name", "item_chosen", "item")
item_values$value_obj = 5

season_alien_values = get_values_and_perf(dat, c("sad_alien_name", "season"), c("sad_alien", "TS"), "alien-same-season")
season_alien_values = merge(season_alien_values, subset(alien_TS_obj, select = c("id", "value_obj")))

all_values_perf = rbind(alien_values, TS_values, item_values, season_alien_values)
all_values_perf

all_files
```
```{r Create pick_aliens data}
if (run_on != "gen_rec") {
  
  # Subset all_files to get pick_aliens (phase 3)
  pick_aliens = subset(all_files, trial_type == "pick-aliens",
                       select = c("subjID", "trial_index", "item_left_name", "item_right_name", "item_chosen_name", "assess", "model_name"))
  # Add column item_unchosen_name
  pick_aliens$item_unchosen_name = with(pick_aliens, ifelse(as.character(item_chosen_name) == as.character(item_right_name), as.character(item_left_name), as.character(item_right_name)))
  pick_aliens$item_left_name = pick_aliens$item_right_name = NULL
  
  # Merge with all_values_perf to get (subj and obj) values and performance for each trial's items
  for (col in c("unchosen", "chosen")) {
    pick_aliens = merge(pick_aliens, all.x = T,
                        subset(all_values_perf, phase == subj_value_phase, select = -c(phase, model_name)),
                        by.x = c("subjID", paste0("item_", col, "_name"), "assess"),
                        by.y = c("subjID", "name", "assess"))
    old_colnames = c("id", "value_subj", "av_ACC", "value_obj")
    new_colnames = paste0(old_colnames, "_", col)
    colnames(pick_aliens)[colnames(pick_aliens) %in% old_colnames] = new_colnames
  }
  
  # Add value difference and ACC difference for each trial
  pick_aliens$value_subj_diff = with(pick_aliens, value_subj_chosen - value_subj_unchosen)
  pick_aliens$value_obj_diff = with(pick_aliens, value_obj_chosen - value_obj_unchosen)
  pick_aliens$av_ACC_diff = with(pick_aliens, av_ACC_chosen - av_ACC_unchosen)
  
  # Order and determine how often participants selected the higher-valued option
  pick_aliens = pick_aliens[order(pick_aliens$subjID, pick_aliens$assess, pick_aliens$item_chosen, pick_aliens$item_unchosen),]
  pick_aliens$selected_better_subj = pick_aliens$value_subj_chosen > pick_aliens$value_subj_unchosen
  pick_aliens$selected_better_obj = pick_aliens$value_obj_chosen > pick_aliens$value_obj_unchosen
  
  # Ddply to get average ACCs and rewards for each condition (aliens, items, seasons, alien-seasons)
  pick_aliens_avs = ddply(pick_aliens,
                          .(subjID, assess, model_name), summarize,
                          value_subj_chosen = mean(value_subj_chosen, na.rm = T),
                          value_subj_unchosen = mean(value_subj_unchosen, na.rm = T),
                          value_subj_diff = mean(value_subj_diff, na.rm = T),
                          value_obj_chosen = mean(value_obj_chosen, na.rm = T),
                          value_obj_unchosen = mean(value_obj_unchosen, na.rm = T),
                          value_obj_diff = mean(value_obj_diff, na.rm = T),
                          av_ACC_diff = mean(av_ACC_diff, na.rm = T),
                          selected_better_subj = mean(selected_better_subj, na.rm = T),
                          selected_better_obj = mean(selected_better_obj, na.rm = T))
  pick_aliens_avs
  
  # Get counts for how often each instance was chosen (alien0, alien1, ..., item0, ..., hot, cold, ..., TS0, TS1, ...)
  pick_aliens_counts_chosen_names = ddply(subset(pick_aliens, !is.na(item_chosen_name)),
                                          .(subjID, assess, item_chosen_name, model_name), summarize,
                                          count_chosen = length(item_chosen_name))
  pick_aliens_counts_unchosen_names = ddply(subset(pick_aliens, !is.na(item_chosen_name)),
                                            .(subjID, assess, item_unchosen_name, model_name), summarize,
                                            count_unchosen = length(item_unchosen_name))
  pick_aliens_counts_names = merge(pick_aliens_counts_chosen_names, pick_aliens_counts_unchosen_names, all = T,
                                   by.x = c("subjID", "assess", "item_chosen_name", "model_name"),
                                   by.y = c("subjID", "assess", "item_unchosen_name", "model_name"))
  colnames(pick_aliens_counts_names)[colnames(pick_aliens_counts_names) == "item_chosen_name"] = "item_chosen"
  pick_aliens_counts_names$type = "names"
  
  pick_aliens_counts_chosen_ids = ddply(subset(pick_aliens, !is.na(id_chosen)),
                                        .(subjID, assess, id_chosen, model_name), summarize,
                                        count_chosen = length(id_chosen))
  pick_aliens_counts_unchosen_ids = ddply(subset(pick_aliens, !is.na(id_unchosen)),
                                          .(subjID, assess, id_unchosen, model_name), summarize,
                                          count_unchosen = length(id_unchosen))
  pick_aliens_counts_ids = merge(pick_aliens_counts_chosen_ids, pick_aliens_counts_unchosen_ids, all = T,
                                 by.x = c("subjID", "assess", "id_chosen", "model_name"),
                                 by.y = c("subjID", "assess", "id_unchosen", "model_name"))
  colnames(pick_aliens_counts_ids)[colnames(pick_aliens_counts_ids) == "id_chosen"] = "item_chosen"
  pick_aliens_counts_ids$type = "ids"
  
  pick_aliens_counts = rbind(pick_aliens_counts_ids, pick_aliens_counts_names)
  pick_aliens_counts$count_chosen[is.na(pick_aliens_counts$count_chosen)] = 0
  pick_aliens_counts$count_unchosen[is.na(pick_aliens_counts$count_unchosen)] = 0
  pick_aliens_counts$chosen_minus_unchosen = with(pick_aliens_counts, count_chosen - count_unchosen)
  pick_aliens_counts
}
```
```{r Plot competition phase}
if (run_on != "gen_rec") {
# Plot difference between chosen and unchosen item in each trial, in terms of subj. value, obj. value, and performance
gg_pick_aliens_value_subj_ = ggplot(pick_aliens, aes(trial_index, value_subj_diff, color = assess)) +
  geom_point() +
  geom_hline(yintercept = 0) +
  labs(x = "Trial", y = "Value chosen minus unchosen (subj.)", color = "") +
  facet_wrap(~ subjID)

gg_pick_aliens_value_obj_ = gg_pick_aliens_value_subj_ + aes(y = value_obj_diff) +
  labs(y = "Value chosen minus unchosen (obj.)")

gg_pick_aliens_ACC_subj_ = gg_pick_aliens_value_subj_ + aes(y = av_ACC_diff) +
  labs(y = "ACC chosen minus unchosen")

# Plot times chosen and unchosen for each instance (item0, item1, ..., alien0, alien1, ...)
gg_pick_aliens_raw_ch = ggplot(pick_aliens_counts, aes(assess, count_chosen, color = item_chosen, group = item_chosen)) +
  stat_summary(fun.data = mean_se, geom = "pointrange", position = position_dodge(width = 0.9)) +
  labs(x = "", y = "# Chosen", color = "") +
  facet_grid(model_name ~ type)
gg_pick_aliens_raw_unch = gg_pick_aliens_raw_ch +
  aes(y = count_unchosen) +
  labs(y = "# Unchosen")
gg_pick_aliens_raw_diff = gg_pick_aliens_raw_ch +
  aes(y = chosen_minus_unchosen) +
  geom_hline(yintercept = 0, linetype = "dotted") +
  labs(y = "# Chosen - # Unchosen")

# Plot value chosen minus unchosen (subj. and obj.)
gg_pick_aliens_value_subj = ggplot(pick_aliens_avs, aes(assess, value_subj_diff, color = subjID)) +
  stat_summary(fun.y = "mean", geom = "bar") +
  stat_summary(fun.data = "mean_se", geom = "pointrange") +
  labs(x = "", y = "Value chosen minus unchosen (subj.)", color = "Participant") +
  geom_point(position = "jitter", alpha = 0.3) +
  facet_grid(model_name ~ .)

gg_pick_aliens_value_obj = gg_pick_aliens_value_subj + aes(y = value_obj_diff) +
  labs(y = "Value chosen minus unchosen (obj.)")

gg_pick_aliens_ACC = gg_pick_aliens_value_subj + aes(y = av_ACC_diff) +
  labs(y = "ACC chosen minus unchosen")

# Percentage of times participants selected the better option in terms of values (subj. and obj.)
gg_pick_aliens_perc_subj = ggplot(pick_aliens, aes(assess, as.numeric(selected_better_subj))) +
  stat_summary(fun.data = "mean_se", geom = "pointrange") +
  labs(x = "", y = "% selected better option (subj. value)") +
  geom_hline(yintercept = 0.5, linetype = "dotted") +
  facet_grid(model_name ~ .)

gg_pick_aliens_perc_obj = gg_pick_aliens_perc_subj + aes(y = as.numeric(selected_better_obj)) +
  labs(x = "", y = "% selected better option (obj. value)")

subset(pick_aliens, is.na(model_name))

if (gg_save) {
  ggsave(file.path(plot_dir, "4gg_pick_aliens_value_subj_.png"), gg_pick_aliens_value_subj_, width = 15, height = 15)
  ggsave(file.path(plot_dir, "4gg_pick_aliens_value_obj_.png"), gg_pick_aliens_value_obj_, width = 15, height = 15)
  ggsave(file.path(plot_dir, "4gg_pick_aliens_ACC_subj_.png"), gg_pick_aliens_ACC_subj_, width = 15, height = 15)
  
  ggsave(file.path(plot_dir, "4gg_pick_aliens_raw_ch.png"), gg_pick_aliens_raw_ch, width = 8, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "4gg_pick_aliens_raw_unch.png"), gg_pick_aliens_raw_unch, width = 8, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "4gg_pick_aliens_raw_diff.png"), gg_pick_aliens_raw_diff, width = 8, height = 3 * length(unique(all_files$model_name)))
  
  ggsave(file.path(plot_dir, "4gg_pick_aliens_value_subj.png"), gg_pick_aliens_value_subj, width = 4, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "4gg_pick_aliens_value_obj.png"), gg_pick_aliens_value_obj, width = 4, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "4gg_pick_aliens_ACC.png"), gg_pick_aliens_ACC, width = 4, height = 3 * length(unique(all_files$model_name)))
  
  ggsave(file.path(plot_dir, "4gg_pick_aliens_perc_subj.png"), gg_pick_aliens_perc_subj, width = 4, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "4gg_pick_aliens_perc_obj.png"), gg_pick_aliens_perc_obj, width = 4, height = 3 * length(unique(all_files$model_name)))
}
}
```
```{r Plot learned values and true objective values}
# Values for aliens, items, TS (subj & obj)
value_plot_ids = ggplot(subset(all_values_perf, assess != "alien-same-season"), aes(assess, value_subj, fill = id)) +
  stat_summary(fun.data = "mean_se", geom = "bar", position = "dodge") +
  stat_summary(fun.data = "mean_se", geom = "pointrange", position = position_dodge(width = 0.9)) +
  labs(y = "Average reward / trial", x = "", fill = "") +
  scale_y_continuous(breaks = seq(0, 10, 2)) +
  facet_grid(model_name ~ phase)
value_plot_ids_subj = value_plot_ids + facet_wrap(phase ~ paste("Subj", subjID))
value_plot_names = value_plot_ids + aes(fill = name)
value_plot_ids_obj = value_plot_ids + aes(y = value_obj) +
  labs(y = "Obj. value")

# Values for each alien in each TS
TS_plot = value_plot_ids +
  aes(substr(id, 2, 2), value_subj, fill = substr(id, 1, 1)) +  # substr(id, 2, 2) = season; substr(id, 1, 2) = alien
  labs(y = "Average reward / trial", x = "TS", fill = "alien")
TS_plot$data = subset(all_values_perf, assess == "alien-same-season")
TS_plot_subj = TS_plot + facet_wrap(~ paste("Subj", subjID))
TS_plot_obj = TS_plot + aes(y = value_obj)

if (gg_save) {
  ggsave(file.path(plot_dir, "0value_plot_ids.png"), value_plot_ids, width = 9, height = 2.5 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "0value_plot_ids_obj.png"), value_plot_ids_obj, width = 9, height = 2.5 * length(unique(all_files$model_name)))
  # ggsave(file.path(plot_dir, "0value_plot_ids_subj.png"), value_plot_ids_subj, width = 15, height = 15)
  ggsave(file.path(plot_dir, "0value_plot_names.png"), value_plot_names, width = 9, height = 2.5 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "0TS_plot.png"), TS_plot, width = 9, height = 2.5 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "0TS_plot_obj.png"), TS_plot_obj, width = 9, height = 2.5 * length(unique(all_files$model_name)))
  # ggsave(file.path(plot_dir, "0TS_plot_subj.png"), TS_plot_subj, width = 15, height = 15)
}
```
```{r Prepare feed_aliens}
# Plotting data: feed_aliens
feed_aliens = subset(all_files, trial_type == "feed-aliens" & block.type != "mixed")

## Add season-alien values (subj. and obj.)
all_values_perf_sub = subset(all_values_perf, phase == subj_value_phase & assess == "alien-same-season")
all_values_perf_sub$TS = substr(all_values_perf_sub$id, 2, 2)
all_values_perf_sub$sad_alien = substr(all_values_perf_sub$id, 1, 1)
all_values_perf_sub = subset(all_values_perf_sub, select = c("subjID", "TS", "sad_alien", "value_subj", "value_obj"))
colnames(all_values_perf_sub)[colnames(all_values_perf_sub) %in% c("value_subj", "value_obj")] = c("item_value_subj", "item_value_obj")

feed_aliens = merge(feed_aliens, all.x = T,
                    subset(all_values_perf_sub, select = c("subjID", "TS", "sad_alien", "item_value_subj", "item_value_obj")),
                    by = c("subjID", "sad_alien", "TS"))

## Add TS values (subj. and obj.)
all_values_perf_sub = subset(all_values_perf, phase ==subj_value_phase & assess == "season")
colnames(all_values_perf_sub)[colnames(all_values_perf_sub) %in% c("id", "value_subj", "value_obj")] = c("TS", "TS_value_subj", "TS_value_obj")

feed_aliens = merge(feed_aliens, all.x = T,
                    subset(all_values_perf_sub, select = c("subjID", "TS", "TS_value_subj", "TS_value_obj")),
                    by = c("subjID", "TS"))

# Add alien_trial_sum column
feed_aliens$alien_trial_sum = NA
feed_aliens = feed_aliens[order(feed_aliens$subjID, feed_aliens$phase, feed_aliens$trial_index, feed_aliens$sad_alien, feed_aliens$TS),]

for (phas in feed_aliens_phases) {
  # Let each phase start at alien_trial == 1
  subs = feed_aliens$phase == phas & !is.na(feed_aliens$alien_trial)
  feed_aliens[subs, "alien_trial"] = feed_aliens[subs, "alien_trial"] - feed_aliens[subs, "alien_trial"][1] + 1
  
  # Add alien_trial_sum: starts at 1 every time a TS is repeated
  feed_aliens[subs, "alien_trial_sum"] = feed_aliens[subs, "alien_trial"]
  n_tr = as.numeric(n_trials[paste("X", phas, sep = "")])
  subs2 = feed_aliens$phase == phas & feed_aliens$alien_trial_sum > n_tr
  while (any(feed_aliens[subs2, "alien_trial_sum"] > n_tr)) {
    feed_aliens[subs2, "alien_trial_sum"] = feed_aliens[subs2, "alien_trial_sum"] - n_tr
    subs2 = feed_aliens$phase == phas & feed_aliens$alien_trial_sum > n_tr
  }
}

# Show feed_aliens
feed_aliens
```
```{r Plot feed_aliens: learning curves for all seasons and check if it depends on reward size / value}
# Make sure that subj & obj values correlate
gg_subj_obj_values = ggplot(subset(feed_aliens, phase != "0Training"), aes(group = subjID)) +
  geom_point(aes(item_value_subj, item_value_obj), color = "red") +
  geom_line(aes(item_value_subj, item_value_obj), color = "red", alpha = 0.3) +
  geom_point(aes(TS_value_subj, TS_value_obj), color = "blue") +
  geom_line(aes(TS_value_subj, TS_value_obj), color = "blue", alpha = 0.3) +
  labs(x = "Subj. values", y = "Obj. values (item: red; TS: blue)") +
  facet_grid(model_name ~ .)

# Plot learning curves dependent on TS value (subj and obj)
gg_learning_curves_TS_value_obj = ggplot(subset(feed_aliens, phase != "0Training"), aes(alien_trial_sum, 100 * ACC, color = TS_value_obj, group = TS_value_obj)) +
  stat_summary(fun.data = mean_se, geom = "pointrange") +
  stat_summary(fun.data = mean_se, geom = "line") +
  geom_hline(yintercept = 100/3, linetype = "dotted") +
  coord_cartesian(y = c(0, 100)) +
  labs(x = "Trial", y = "% correct", color = "Value") +
  theme(legend.position = "none") +
  facet_grid(model_name ~ phase)

gg_learning_curves_TS_value_subj = gg_learning_curves_TS_value_obj + aes(color = round(TS_value_subj), group = round(TS_value_subj))
  
# Plot learning curves dependent on item value (subj and obj)
gg_learning_curves_item_value_obj = gg_learning_curves_TS_value_obj + aes(color = item_value_obj, group = item_value_obj)
gg_learning_curves_item_value_subj = gg_learning_curves_TS_value_obj + aes(color = round(item_value_subj), group = round(item_value_subj))

# Plot learning curves by repetition
gg_learning_curves_rep = gg_learning_curves_TS_value_obj +
  aes(group = repetition, color = repetition) +
  labs(x = "Trial", color = "Repetition") +
  facet_grid(phase ~ TS)

# Plot different items next to each other
gg_learning_curves_wide = ggplot(subset(feed_aliens, phase != "0Training"), aes(alien_trial_sum, 100 * ACC, color = TS, shape = sad_alien)) +
  stat_summary(fun.data = mean_se, geom = "pointrange") +
  stat_summary(fun.data = mean_se, geom = "line") +
  labs(x = "Trial", y = "% correct") +
  coord_cartesian(y = c(0, 100)) +
  facet_grid(phase ~ paste("It. val.", item_value_obj))

if (gg_save) {
  ggsave(file.path(plot_dir, "/2gg_subj_obj_values.png"), gg_subj_obj_values, width = 3, height = 1.5 * length(unique(all_files$model_name)))
  
  ggsave(file.path(plot_dir, "/2gg_learning_curves_TS_value_obj.png"), gg_learning_curves_TS_value_obj, width = 10, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "/2gg_learning_curves_TS_value_subj.png"), gg_learning_curves_TS_value_subj, width = 10, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "/2gg_learning_curves_item_value_obj.png"), gg_learning_curves_item_value_obj, width = 10, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "/2gg_learning_curves_item_value_subj.png"), gg_learning_curves_item_value_subj, width = 10, height = 3 * length(unique(all_files$model_name)))
  
  ggsave(file.path(plot_dir, "/2gg_learning_curves_rep.png"), gg_learning_curves_rep, width = 10, height = 10)
  ggsave(file.path(plot_dir, "/2gg_learning_curves_wide.png"), gg_learning_curves_wide, width = 10, height = 5)
}
```
```{r Prepare ACC_1back_dat (ACC_1back_self and ACC_1back_other)}
# Regression data: ACC_1back_dat
## Bring in the right order for regression: each line must be the predictor of the immediate next line!
feed_aliens = feed_aliens[order(feed_aliens$subjID, feed_aliens$phase, feed_aliens$sad_alien, feed_aliens$TS, feed_aliens$alien_trial),]
ACC_1back_dat = subset(feed_aliens, phase != "0Training", select = c("subjID", "phase", "sad_alien", "TS", "reward", "TS_value_subj", "TS_value_obj", "item_value_subj", "item_value_obj", "alien_trial_sum", "alien_trial", "trial_index", "repetition", "ACC", "model_name"))

ACC_1back_self = c(NA, ACC_1back_dat$ACC[1:length(ACC_1back_dat$ACC)-1])
ACC_1back_self[ACC_1back_dat$alien_trial_sum == 1] = NA
ACC_1back_dat$ACC_1back_self = ACC_1back_self

rew_1back_self = c(NA, ACC_1back_dat$reward[1:length(ACC_1back_dat$reward)-1])
rew_1back_self[ACC_1back_dat$alien_trial_sum == 1] = NA
ACC_1back_dat$rew_1back_self = rew_1back_self

others_ACC_1back_dat = data.frame()
for (alien in unique(ACC_1back_dat$sad_alien)) {
  alien_ACC_1back_dat = ddply(subset(ACC_1back_dat, sad_alien != alien),
                    .(subjID, phase, TS, alien_trial, alien_trial_sum), summarize,
                    ACC_others = mean(ACC, na.rm = T))
  alien_ACC_1back_dat$sad_alien = alien
  others_ACC_1back_dat = rbind(others_ACC_1back_dat, alien_ACC_1back_dat)
}
others_ACC_1back_dat = others_ACC_1back_dat[order(others_ACC_1back_dat$subjID, others_ACC_1back_dat$phase, others_ACC_1back_dat$sad_alien, others_ACC_1back_dat$TS, others_ACC_1back_dat$alien_trial),]
ACC_1back_others = c(NA, others_ACC_1back_dat$ACC_others[1:length(others_ACC_1back_dat$ACC_others)-1])
ACC_1back_others[others_ACC_1back_dat$alien_trial_sum == 1] = NA
others_ACC_1back_dat$ACC_1back_others = ACC_1back_others

ACC_1back_dat = merge(others_ACC_1back_dat, ACC_1back_dat,  # sanity check: cloudy ACC_1back_dat should have 12000 rows: 50 subj * 20 alien_trials * 3 TS * 4 sad_aliens
                 by = c("subjID", "phase", "TS", "alien_trial", "alien_trial_sum", "sad_alien"))
ACC_1back_dat$TS = factor(ACC_1back_dat$TS)
ACC_1back_dat$sad_alien = factor(ACC_1back_dat$sad_alien)
summary(ACC_1back_dat)
```
```{r Plot feed_alien_trial1: How well do participants infer TS}
# Get data
feed_alien_trial1 = subset(feed_aliens, alien_trial_sum == 1, select = c(subjID, model_name, sad_alien, TS, trial_index, phase, ACC, block))
feed_alien_trial1 = feed_alien_trial1[order(feed_alien_trial1$subjID, feed_alien_trial1$trial_index),]

# Add n_seen_aliens and n-back columns (I wish there was a better way to do this, with rollmean or so, but rollmean sets everything before NA..)
for (subj in unique(feed_alien_trial1$subjID)) {
  for (blocki in unique(feed_alien_trial1$block)) {
    sub_subj_block = feed_alien_trial1$block == blocki & feed_alien_trial1$subjID == subj
    feed_alien_trial1[sub_subj_block, "n_seen_aliens"] = 0:3
    for (n in 1:(n_aliens-1)) {
      col = paste0("back", n)
      if (mean(sub_subj_block) > 0) {
        ACC = feed_alien_trial1[sub_subj_block, "ACC"]
        ACC_aliens_before = c(rep(NA, n), ACC[1:(length(ACC)-n)])
        feed_alien_trial1[sub_subj_block, col] = ACC_aliens_before
      }
    }
  }
}

# Add cum_ACC column = How many trials has participants gotten right up until (but not including) the current trial?
feed_alien_trial1$cum_ACC = rowSums(feed_alien_trial1[,paste("back", 1:(n_aliens-1), sep = "")], na.rm = T)
feed_alien_trial1$cum_ACC_ = feed_alien_trial1$cum_ACC
feed_alien_trial1$cum_ACC_[feed_alien_trial1$cum_ACC %in% c(2, 3)] = "2-3"

gg_prev_ACC = ggplot(feed_alien_trial1, aes(cum_ACC_, 100 * ACC)) +  # , color = cum_ACC_1back, group = cum_ACC_1back
  stat_summary(fun.data = mean_se, geom = "bar") +
  stat_summary(fun.data = mean_se, aes(color = TS, group = TS), geom = "pointrange") +
  stat_summary(fun.data = mean_se, aes(color = TS, group = TS), geom = "line") +
  geom_hline(yintercept = 100/3, linetype = "dotted") +
  coord_cartesian(ylim = c(0, 100)) +
  labs(x = "# previous correct trials", y = "% correct", color = "TS") +
  facet_grid(model_name ~ phase)
gg_prev_seen = gg_prev_ACC + aes(x = n_seen_aliens) + labs(x = "# other aliens seen")

if (gg_save) {
  ggsave(file.path(plot_dir, "/2gg_prev_ACC.png"), gg_prev_ACC, width = 10, height = 2.5 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "/2gg_prev_seen.png"), gg_prev_seen, width = 10, height = 2.5 * length(unique(all_files$model_name)))
}
```
```{r Add prev_TS and prev_notTS to feed_aliens (perseverance stuff)}
# Get data that shows which choices correspond to one of the 3 TS, and which don't
correct_TS = ddply(subset(all_files, ACC == 1 & season %in% c("cold", "hot", "rainy")),
                      .(TS, sad_alien), summarize,
                      item_chosen = item_chosen[1])
correct_TS$ACC = 1
all_TS = expand.grid(TS = unique(correct_TS$TS), sad_alien = unique(correct_TS$sad_alien), item_chosen = unique(correct_TS$item_chosen))
corincor_TS = merge(correct_TS, all_TS, all.y = T)
corincor_TS$ACC[is.na(corincor_TS$ACC)] = 0

# Add columns ACC0, ACC1, ACC2 (accuracy for each TS to each trial)
for (TSi in unique(corincor_TS$TS)) {
  feed_aliens = merge(feed_aliens, subset(corincor_TS, TS == TSi, select = -TS),
        by = c("sad_alien", "item_chosen"),
        all.x = T,
        suffixes = c("", TSi))
}
feed_aliens$ACCNone = with(feed_aliens, ACC0 + ACC1 + ACC2 == 0)  # Actions that are incorrect in each of the three TS
feed_aliens = feed_aliens[order(feed_aliens$subjID, feed_aliens$trial_index),]

# Add columns prev_TS and prev_notTS
feed_aliens$prev_TS = NA
feed_aliens$prev_notTS = NA
prev_TS = NA

for (subj in unique(feed_aliens$subjID)) {
  for (blocki in unique(subset(feed_aliens, subjID == subj)$block)) {
    
    subj_block_sub = feed_aliens$subjID == subj & feed_aliens$block == blocki
    current_TS = as.numeric(as.character(feed_aliens[subj_block_sub, "TS"][1]))
    
    if (is.na(prev_TS)) {
      prev_notTS = NA
    } else {
      prev_notTS = 3 - current_TS - prev_TS  # [TS]0 + [TS]1 + [TS]2 = 3
    }
    
    feed_aliens[subj_block_sub, "prev_TS"] = prev_TS
    feed_aliens[subj_block_sub, "prev_notTS"] = prev_notTS
    
    prev_TS = current_TS
  }
}

# Add columns ACC_prev_TS and ACC_prev_notTS
feed_aliens$ACC_prev_TS = NA
feed_aliens$ACC_prev_notTS = NA
for (TSi in 0:2) {
  rows_prev = !is.na(feed_aliens$prev_TS) & feed_aliens$prev_TS == TSi
  rows_prev_not = !is.na(feed_aliens$prev_notTS) & feed_aliens$prev_notTS == TSi
  col = paste0("ACC", TSi)
  feed_aliens[rows_prev, "ACC_prev_TS"] = feed_aliens[rows_prev, col]
  feed_aliens[rows_prev_not, "ACC_prev_notTS"] = feed_aliens[rows_prev_not, col]
}

feed_aliens[order(feed_aliens$subjID, feed_aliens$trial_index), c("subjID", "sad_alien", "TS", "ACC", "ACC0", "ACC1", "ACC2", "prev_TS", "prev_notTS", "ACC_prev_TS", "ACC_prev_notTS")]
```
```{r Create persev_dat and plot perseverance mistakes}
# Melt feed_aliens along ACC0, ACC1, ACC2, ACCNone
persev_dat_wide = subset(feed_aliens, select = c("subjID", "trial_index", "phase", "alien_trial", "alien_trial_sum", "model_name", "sad_alien", "TS", "ACC", "ACC_prev_TS", "ACC_prev_notTS", "ACC0", "ACC1", "ACC2", "ACCNone", "TS_value_obj", "TS_value_subj", "item_value_subj", "item_value_obj", "repetition", "alien_trial_sum"))
persev_dat = melt(subset(persev_dat_wide, select = -c(ACC, ACC_prev_TS, ACC_prev_notTS)), measure.vars = c("ACC0", "ACC1", "ACC2", "ACCNone"), variable.name = "ACC_TS", value.name = "ACC")
persev_dat$current_TS = F
for (TSi in 0:2) {
  persev_dat$current_TS[persev_dat$TS == TSi & persev_dat$ACC_TS == paste0("ACC", TSi)] = T
}
summary(persev_dat)

gg_otherTS_ACC = ggplot(persev_dat, aes(alien_trial, 100 * ACC, color = factor(ACC_TS))) +
  stat_summary(fun.data = mean_se, geom = "pointrange") +
  geom_hline(yintercept = 100/3, linetype = "dotted") +
  geom_hline(yintercept = 200/12, linetype = "dotted", color = "purple") +
  coord_cartesian(y = c(0, 100)) +
  labs(x = "Trial", y = "% chosen", color = "") +
  facet_grid(phase ~ TS)

gg_otherTS_ACC_value = ggplot(persev_dat, aes(alien_trial, 100 * ACC, color = factor(TS_value_obj), group = sad_alien)) +
  stat_summary(fun.data = mean_se, geom = "pointrange") +
  geom_hline(yintercept = 100/3, linetype = "dotted") +
  coord_cartesian(y = c(0, 100)) +
  labs(x = "Trial", y = "% chosen", color = "Value") +
  facet_grid(factor(persev_dat$TS) ~ ACC_TS)#, labels = c("TS0", "TS1", "TS2")

gg_otherTS_ACC_alien = gg_otherTS_ACC_value +
  aes(color = factor(sad_alien)) +
  labs(color = "Alien")

persev_dat2 = melt(subset(persev_dat_wide, select = -c(ACC0, ACC1, ACC2, ACCNone)), measure.vars = c("ACC", "ACC_prev_TS", "ACC_prev_notTS"), variable.name = "ACC_TS", value.name = "ACC")
gg_prevTS_ACC = gg_otherTS_ACC_value +
  aes(color = factor(value_subj)) +
  facet_grid(TS ~ ACC_TS)
gg_prevTS_ACC$data = persev_dat2

# Remove trials that count as "intrusion errors" although they are correct in the current TS
persev_dat$ACC[persev_dat$sad_alien == 3 & persev_dat$TS == 0 & persev_dat$ACC_TS == "ACC2"] = NA
persev_dat$ACC[persev_dat$sad_alien == 3 & persev_dat$TS == 2 & persev_dat$ACC_TS == "ACC0"] = NA
persev_dat$ACC[persev_dat$sad_alien == 0 & persev_dat$TS == 2 & persev_dat$ACC_TS == "ACC1"] = NA
persev_dat$ACC[persev_dat$sad_alien == 0 & persev_dat$TS == 1 & persev_dat$ACC_TS == "ACC2"] = NA

persev_dat2$ACC[persev_dat2$sad_alien == 3 & persev_dat2$TS == 0 & persev_dat2$ACC_TS == "ACC_prev_TS"] = NA
persev_dat2$ACC[persev_dat2$sad_alien == 3 & persev_dat2$TS == 2 & persev_dat2$ACC_TS == "ACC_prev_TS"] = NA
persev_dat2$ACC[persev_dat2$sad_alien == 0 & persev_dat2$TS == 2 & persev_dat2$ACC_TS == "ACC_prev_TS"] = NA
persev_dat2$ACC[persev_dat2$sad_alien == 0 & persev_dat2$TS == 1 & persev_dat2$ACC_TS == "ACC_prev_TS"] = NA

persev_dat2$ACC[persev_dat2$sad_alien == 3 & persev_dat2$TS == 0 & persev_dat2$ACC_TS == "ACC_prev_notTS"] = NA
persev_dat2$ACC[persev_dat2$sad_alien == 3 & persev_dat2$TS == 2 & persev_dat2$ACC_TS == "ACC_prev_notTS"] = NA
persev_dat2$ACC[persev_dat2$sad_alien == 0 & persev_dat2$TS == 2 & persev_dat2$ACC_TS == "ACC_prev_notTS"] = NA
persev_dat2$ACC[persev_dat2$sad_alien == 0 & persev_dat2$TS == 1 & persev_dat2$ACC_TS == "ACC_prev_notTS"] = NA

# How often do intrusions occur compared to just random mistakes?  (Question: Am I counting errors twice that are correct in more than one TS??)
persev_dat$none_or_TS = ifelse(persev_dat$ACC_TS == "ACCNone", "None", "TS")
subj_av = ddply(subset(persev_dat, !current_TS), .(subjID, none_or_TS), summarize,
      ACC = sum(ACC, na.rm = T))
subj_av = reshape(subj_av, direction = "wide", timevar = "none_or_TS", idvar = "subjID")
subj_av$fraction_TS_errors = with(subj_av, ACC.TS / (ACC.None + ACC.TS))
plot(subj_av$fraction_TS_errors - 6/8)
t.test(subj_av$fraction_TS_errors - 6/8)
grand_av = ddply(subj_av, .(), summarize,
      fraction_TS_errors = mean(fraction_TS_errors, na.rm = T))

gg_otherTS_ACC2 = gg_otherTS_ACC
gg_otherTS_ACC2$data = persev_dat
gg_otherTS_ACC2 = gg_otherTS_ACC2 + facet_grid(phase ~ model_name)
gg_otherTS_ACC_value2 = gg_otherTS_ACC_value
gg_otherTS_ACC_value2$data = persev_dat
gg_otherTS_ACC_alien2 = gg_otherTS_ACC_alien
gg_otherTS_ACC_alien2$data = persev_dat
gg_prevTS_ACC2 = gg_prevTS_ACC + aes(x = alien_trial_sum, color = factor(ACC_TS, labels = c("Current TS", "Previous TS", "Other TS")), group = ACC_TS) + facet_grid(model_name ~ phase) + labs(x = "Trial", color = "")
gg_prevTS_ACC2$data = persev_dat2

gg_otherTS_ACC3 = gg_otherTS_ACC2 + aes(x = alien_trial_sum, color = ACC_TS, shape = factor(current_TS, labels = c("Other TS", "Current TS"))) +
  labs(x = "", color = "", shape = "") +
  facet_grid(model_name ~ phase)
gg_otherTS_ACC3$data = persev_dat
gg_otherTS_ACC4 = gg_otherTS_ACC3 + aes(x = "") + theme(legend.position = "none")

if (gg_save) {
  ggsave(file.path(plot_dir, "/2gg_otherTS_ACC.png"), gg_otherTS_ACC, width = 10, height = 9)
  # ggsave(paste(plot_dir, "/2gg_otherTS_ACC_value_", phas, ".png", sep = ""), gg_otherTS_ACC_value, width = 9, height = 6)
  # ggsave(paste(plot_dir, "/2gg_otherTS_ACC_alien_", phas, ".png", sep = ""), gg_otherTS_ACC_alien, width = 9, height = 6)
  # ggsave(paste(plot_dir, "/2gg_prevTS_ACC_", phas, ".png", sep = ""), gg_prevTS_ACC, width = 9, height = 7)
  
  # ggsave(paste(plot_dir, "/2gg_otherTS_ACC2_", phas, ".png", sep = ""), gg_otherTS_ACC2, width = 9, height = 3)
  ggsave(file.path(plot_dir, "/2gg_otherTS_ACC3.png"), gg_otherTS_ACC3, width = 10, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "/2gg_otherTS_ACC4.png"), gg_otherTS_ACC4, width = 5, height = 3 * length(unique(all_files$model_name)))
  # ggsave(paste(plot_dir, "/2gg_otherTS_ACC_value2_", phas, ".png", sep = ""), gg_otherTS_ACC_value2, width = 9, height = 6)
  # ggsave(paste(plot_dir, "/2gg_otherTS_ACC_alien2_", phas, ".png", sep = ""), gg_otherTS_ACC_alien2, width = 9, height = 6)
  ggsave(file.path(plot_dir, "/2gg_prevTS_ACC2.png"), gg_prevTS_ACC2, width = 10, height = 3 * length(unique(all_files$model_name)))
}
```
```{r Run intrusion regression models}
subjwise_regr_coefs = data.frame()
all_regressions = data.frame()
value_obj_predictors = c("TS_value_obj", "item_value_obj")
predictors_no_interest = c("repetition", "alien_trial_sum")

# Subjectwise / agentwise regression coefficients
for (subj in unique(persev_dat$subjID)) {
  for (phas in feed_aliens_phases) {
  
    dat = subset(persev_dat, current_TS == F & ACC_TS != "None" & phase == phas & subjID == subj)
    
    for (predictor in c(value_obj_predictors, predictors_no_interest)) {
      pred_dat = dat[,predictor]
      dat[,paste0(predictor, "_zscored")] = (pred_dat - mean(pred_dat, na.rm = T)) / sd(pred_dat, na.rm = T)
    }
    
    intrusion_formula = paste("ACC ~", paste(paste0(value_obj_predictors, "_zscored"), collapse = " + "), "+", paste(paste0(predictors_no_interest, "_zscored"), collapse = " + "))
    
    intrusion_mod = glm(as.formula(intrusion_formula),
        family = binomial,
        data = dat)
    intrusion_coefs = summary(intrusion_mod)$coef
    intrusion_coefs = cbind(subjID = subj, phase = phas, regr_model = "intrusions", predictor = rownames(intrusion_coefs), as.data.frame(intrusion_coefs, row.names = F))
    subjwise_regr_coefs = rbind(subjwise_regr_coefs, intrusion_coefs)
  }
}

# One joint model for all agents
if (run_regression) {
  for (model_namei in unique(persev_dat$model_name)) {
    for (phas in unique(persev_dat$phase)) {  # I could also just run one single regression model and include phase as a predictor
      
      others = subset(persev_dat, current_TS == F & ACC_TS != "None" & phase == phas & model_name == model_namei)
      others$ACC_TS = factor(others$ACC_TS, levels = c("ACC0", "ACC1", "ACC2"), labels = 0:2)
    
      # Not sure what the predictors should be here?
      intrusions_form = paste("ACC ~", paste(value_obj_predictors, collapse = " + "), "+", paste(predictors_no_interest, collapse = " + "),
                              "+ (", paste(value_obj_predictors, collapse = " + "), "+", paste(predictors_no_interest, collapse = " + "), "| subjID)")
      
      intrusion_glmer = glmer(as.formula(intrusions_form),
                        family = binomial,
                        data = others,
                        na.action = na.omit,
                        control = glmerControl(optimizer = 'bobyqa', optCtrl = list(maxfun = 1e6)))
      glmer_coefs = summary(intrusion_glmer)$coef
      glmer_coefs = cbind(model_name = model_namei, phase = phas, regr_model = "intrusions", predictor = rownames(glmer_coefs), as.data.frame(glmer_coefs, row.names = F))
      all_regressions = rbind(all_regressions, glmer_coefs)
    }
  }
}
```
```{r Run 1back_sef 1back_other regression models}
regression_plot = TS_plot + aes(TS, 100 * ACC, fill = sad_alien) + labs(y = "% correct", fill = "Alien")
regression_plot$data = ACC_1back_dat
ggsave(file.path(plot_dir, "3regression_plot.png"), regression_plot, width = 10, height = 3 * length(unique(all_files$model_name)))

nback_predictors = c("ACC_1back_self", "ACC_1back_others")

for (subj in unique(ACC_1back_dat$subjID)) {
  for (phas in feed_aliens_phases) {
  
    dat = subset(ACC_1back_dat, subjID == subj & phase == phas)
    
    for (predictor in c(nback_predictors, predictors_no_interest)) {
      pred_dat = dat[,predictor]
      dat[,paste0(predictor, "_zscored")] = (pred_dat - mean(pred_dat, na.rm = T)) / sd(pred_dat, na.rm = T)
    }
    
    value_formula = paste("ACC ~", paste(paste0(value_obj_predictors, "_zscored"), collapse = " + "), "+", paste(paste0(predictors_no_interest, "_zscored"), collapse = " + "))
    nback_formula = paste("ACC ~", paste(paste0(nback_predictors, "_zscored"), collapse = " + "), "+", paste(paste0(predictors_no_interest, "_zscored"), collapse = " + "))
    
    value_mod = glm(as.formula(value_formula),
        family = binomial,
        data = dat)
    value_coefs = summary(value_mod)$coef
    value_coefs = cbind(subjID = subj, phase = phas, regr_model = "ACC_value", predictor = rownames(value_coefs), as.data.frame(value_coefs, row.names = F))
    
    nback_mod = update(value_mod, as.formula(nback_formula))
    nback_coefs = summary(nback_mod)$coef
    nback_coefs = cbind(subjID = subj, phase = phas, regr_model = "ACC_nback", predictor = rownames(nback_coefs), as.data.frame(nback_coefs, row.names = F))
    
    subjwise_regr_coefs = rbind(subjwise_regr_coefs, value_coefs, nback_coefs)
  }
}
summary(subjwise_regr_coefs)

if (run_regression) {
  for (model_namei in unique(ACC_1back_dat$model_name)) {
    for (phas in feed_aliens_phases) {
      
      value_formula = paste("ACC ~", paste(value_obj_predictors, collapse = " + "), "+", paste(predictors_no_interest, collapse = " + "),
                            "+ (", paste(value_obj_predictors, collapse = " + "), "+", paste(predictors_no_interest, collapse = " + "), "| subjID)")
      nback_formula = paste("ACC ~", paste(nback_predictors, collapse = " + "), "+", paste(predictors_no_interest, collapse = " + "),
                            "+ (", paste(nback_predictors, collapse = " + "), "+", paste(predictors_no_interest, collapse = " + "), "| subjID)")
      rew1back_formula = paste("ACC ~ rew_1back_self +", paste(predictors_no_interest, collapse = " + "),
                             "+ (rew_1back_self + ",  paste(predictors_no_interest, collapse = " + "), "| subjID)")
      
      value_glmer = glmer(as.formula(value_formula),
                        family = binomial,
                        data = subset(ACC_1back_dat, phase == phas & model_name == model_namei),
                        na.action = na.omit,
                        control = glmerControl(optimizer = 'bobyqa', optCtrl = list(maxfun = 1e6)))
      value_coefs = summary(value_glmer)$coef
      value_coefs = cbind(model_name = model_namei, phase = phas, regr_model = "ACC_value", predictor = rownames(value_coefs), as.data.frame(value_coefs, row.names = F))

      nback_glmer = update(value_glmer, formula = as.formula(nback_formula))
      nback_coefs = summary(nback_glmer)$coef
      nback_coefs = cbind(model_name = model_namei, phase = phas, regr_model = "ACC_nback", predictor = rownames(nback_coefs), as.data.frame(nback_coefs, row.names = F))
      
      rew1back_glmer = update(value_glmer, formula = as.formula(rew1back_formula))
      rew1back_coefs = summary(rew1back_glmer)$coef
      rew1back_coefs = cbind(model_name = model_namei, phase = phas, regr_model = "ACC_rewback", predictor = rownames(rew1back_coefs), as.data.frame(rew1back_coefs, row.names = F))
      
      all_regressions = rbind(all_regressions, value_coefs, nback_coefs, rew1back_coefs)
    }
  }
}
summary(all_regressions)
```
```{r Create Rainbow season data rainbow_aliens and rainbow_sum_l}
# Create data.frame that shows accuracy according to each of the 3 TS, none, and missed trials
all_ACCs = expand.grid(sad_alien = unique(feed_aliens$sad_alien), item_chosen = unique(feed_aliens$item_chosen))
correct_ones = ddply(subset(all_files, ACC == 1 & season %in% c("cold", "hot", "rainy")),
                    .(TS, sad_alien), summarize,
                    item_chosen = item_chosen[1])
correct_ones$ACC = 1
correct_ones = reshape(correct_ones, direction = "wide", timevar = "TS", idvar = c("sad_alien", "item_chosen")) #, "value"

all_ACCs = merge(all_ACCs, correct_ones, all.x = T)
all_ACCs$ACC.Missed = ifelse(all_ACCs$item_chosen == "NaN", 1, 0)
all_ACCs$ACC.None = with(all_ACCs, (is.na(ACC.0)) * (is.na(ACC.1)) * (is.na(ACC.2)) * (1 - ACC.Missed))
all_ACCs$ACC.02 = with(all_ACCs, ACC.0 * ACC.2)
all_ACCs$ACC.12 = with(all_ACCs, ACC.1 * ACC.2)
all_ACCs$ACC.only0 = with(all_ACCs, ACC.0 * (is.na(ACC.02)))
all_ACCs$ACC.only1 = with(all_ACCs, ACC.1 * (is.na(ACC.12)))
all_ACCs$ACC.only2 = with(all_ACCs, ACC.2 * (is.na(ACC.12)) * (is.na(ACC.02)))

# Add all_ACCs columns to rainbow_data
rainbow_aliens = merge(subset(all_files, phase == "5RainbowSeason", select = c("subjID", "sad_alien", "item_chosen", "trial_index")), all.x = T, all_ACCs)
rainbow_aliens = rainbow_aliens[order(rainbow_aliens$subjID, rainbow_aliens$trial_index),]

# Create rainbow_sum (count how many action would be correct in each TS)
rainbow_sum = ddply(rainbow_aliens, .(subjID), summarize,
                    `0` = sum(ACC.only0, na.rm = T),
                    `1` = sum(ACC.only1, na.rm = T),
                    `2` = sum(ACC.only2, na.rm = T),
                    `0and2` = sum(ACC.02, na.rm = T),
                    `1and2` = sum(ACC.12, na.rm = T),
                    Missed = sum(ACC.Missed, na.rm = T),
                    None = sum(ACC.None, na.rm = T))

# Create rainbow_sum_l (put all TS into a single column)
rainbow_sum_l = melt(rainbow_sum, id.vars = c("subjID"), variable.name = "TS", value.name = "times_chosen")

# Add frac_chosen column
rainbow_sum_l$frac_chosen = rainbow_sum_l$times_chosen  # 1and2, 0and2 have only one opportunity
rainbow_sum_l$frac_chosen[rainbow_sum_l$TS %in% c("0", "1")] = rainbow_sum_l$times_chosen[rainbow_sum_l$TS %in% c("0", "1")] / 3  # 3 opportunities to pick TS0 and TS1
rainbow_sum_l$frac_chosen[rainbow_sum_l$TS %in% c("None", "2")] = rainbow_sum_l$times_chosen[rainbow_sum_l$TS %in% c("None", "2")] / 2  # 2 opportunities to pick TS0 and TS1
rainbow_sum_l$frac_chosen[rainbow_sum_l$TS == "Missed"] = NA

# Add values (subj and obj) and task performance column
all_values_perf_sub = subset(all_values_perf, assess == "season" & phase == "Refresher3", select = c("subjID", "name", "id", "value_subj", "value_obj", "av_ACC"))
rainbow_sum_l = merge(rainbow_sum_l, all.x = T,
                      all_values_perf_sub,
                      by.x = c("subjID", "TS"),
                      by.y = c("subjID", "id"))
colnames(rainbow_sum_l)[colnames(rainbow_sum_l) %in% c("value_subj", "value_obj")] = c("TS_value_subj", "TS_value_obj")
if (run_on == "humans") {
  rainbow_sum_l$model_name = "humans"
} else {
  model_names = subset(parameter_dat, select = c("subjID", "model_name"))
  rainbow_sum_l = merge(rainbow_sum_l, model_names, by = "subjID", all.x = T)
}
# Add objective alien values
rainbow_sum_l$alien_values_obj = NA
rainbow_sum_l$alien_values_obj[rainbow_sum_l$TS == 0] = mean(c(6, 5, 4))
rainbow_sum_l$alien_values_obj[rainbow_sum_l$TS == 1] = mean(c(3, 7, 8))
rainbow_sum_l$alien_values_obj[rainbow_sum_l$TS == 2] = mean(c(3, 3))
rainbow_sum_l
```
```{r Plot rainbow season data}
# Look at how often each TS is chosen on average
gg_rainbow_avs = ggplot(rainbow_sum_l, aes(TS)) +
  stat_summary(aes(y = frac_chosen), color = "red", fun.data="mean_se", geom="pointrange") +
  stat_summary(aes(y = times_chosen), color = "blue", fun.data="mean_se", geom="pointrange") +
  labs(y = "Fraction (red); Times chosen (blue)") +
  facet_grid(model_name ~ .)

# Histogram of how often the three TS are chosen
gg_rainbow_TS = ggplot(subset(rainbow_sum_l, TS %in% c("0", "1", "2", "None")), aes(times_chosen, fill = TS)) +
  geom_histogram(stat = "density", position = "identity", alpha = 0.8) +
  labs(x = "# TS choices") +
  facet_grid(model_name ~ .)

gg_rainbow_TS_full = gg_rainbow_TS
gg_rainbow_TS_full$data = rainbow_sum_l

# Histogram, split by TS values (obj and subj) rather than TS identity
gg_rainbow_value_obj = gg_rainbow_TS + aes(fill = TS_value_obj, group = TS_value_obj) +
    labs(x = "# TS choices", fill = "Obj. TS value")
gg_rainbow_value_obj$data = subset(rainbow_sum_l, !is.na(TS_value_obj))

rainbow_sum_l$TS_value_subj_cat = round(rainbow_sum_l$TS_value_subj * 2) / 2
gg_rainbow_value_subj = gg_rainbow_TS + aes(color = TS_value_subj_cat, fill = TS_value_subj_cat, group = TS_value_subj_cat) +
  labs(color = "Subj. TS value", fill = "Subj. TS value")
gg_rainbow_value_subj$data = subset(rainbow_sum_l, !is.na(TS_value_subj))

# Histogram, split by ACC rather than TS
rainbow_sum_l$av_ACC_cat = round(rainbow_sum_l$av_ACC * 5) / 5
gg_rainbow_ACC = gg_rainbow_TS + aes(fill = av_ACC_cat, group = av_ACC_cat) +
    labs(x = "# TS choices", fill = "TS performance")
gg_rainbow_ACC$data = subset(rainbow_sum_l, !is.na(av_ACC_cat))

if (gg_save) {
  ggsave(file.path(plot_dir, "5gg_rainbow_avs.png"), gg_rainbow_avs, width = 5, height = 3 * length(unique(all_files$model_name)))
  
  ggsave(file.path(plot_dir, "5gg_rainbow_TS.png"), gg_rainbow_TS, width = 5, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "5gg_rainbow_TS_full.png"), gg_rainbow_TS_full, width = 5, height = 3 * length(unique(all_files$model_name)))
  
  ggsave(file.path(plot_dir, "5gg_rainbow_value_obj.png"), gg_rainbow_value_obj, width = 5, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "5gg_rainbow_value_subj.png"), gg_rainbow_value_subj, width = 5, height = 3 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "5gg_rainbow_ACC.png"), gg_rainbow_ACC, width = 5, height = 3 * length(unique(all_files$model_name)))
}
```
```{r Run rainbow regression models}
subjwise_regr_coefs
# Model: frac_chosen ~ TS_value_obj + alien_values_obj + TS_ACC
ACC_1back_dat = subset(rainbow_sum_l, TS %in% c("0", "1", "2"))
ACC_1back_dat$TS = factor(ACC_1back_dat$TS)
contrasts(ACC_1back_dat$TS) = -contr.poly(3)

for (subj in unique(ACC_1back_dat$subjID)) {
  
  dat = subset(ACC_1back_dat, subjID == subj)
  
  for (predictor in value_obj_predictors) {
    pred_dat = dat[,predictor]
    dat[,paste0(predictor, "_zscored")] = (pred_dat - mean(pred_dat, na.rm = T)) / sd(pred_dat, na.rm = T)
  }
  
  rainbow_formula = paste("frac_chosen ~", paste(paste0(value_obj_predictors, "_zscored"), collapse = " + "))
    
  rainbow_mod = lm(as.formula(rainbow_formula),
                   dat,
                   na.action=na.omit)
  rainbow_coefs = summary(rainbow_mod)$coef
  rainbow_coefs = cbind(subjID = subj, phase = "5RainbowSeason", regr_model = "rainbow", predictor = rownames(rainbow_coefs), as.data.frame(rainbow_coefs, row.names = F))
  colnames(rainbow_coefs) = colnames(subjwise_regr_coefs)
  subjwise_regr_coefs = rbind(subjwise_regr_coefs, rainbow_coefs)
}

# Were more TS-related items selected than expected based on chance?
TS_choices = 12 - rainbow_sum$Missed - rainbow_sum$None
Valid_choices = 12 - rainbow_sum$Missed
mean(TS_choices)
mean(Valid_choices)
mean(TS_choices / Valid_choices)
t.test(TS_choices - 10 / 12 * Valid_choices)

None_choices = rainbow_sum$None
mean(None_choices / Valid_choices)
t.test(None_choices - 2 / 12 * Valid_choices)

# mean(rainbow_sum$TS0)
# mean(rainbow_sum$TS0 / Valid_choices)
# t.test(rainbow_sum$TS0 - 3 / 12 * Valid_choices)
# mean(rainbow_sum$TS1)
# mean(rainbow_sum$TS1 / Valid_choices)
# t.test(rainbow_sum$TS1 - 3 / 12 * Valid_choices)
# t.test(rainbow_sum$TS0 - rainbow_sum$TS1)
# mean(rainbow_sum$TS2)
# mean(rainbow_sum$TS2 / Valid_choices)
# t.test(rainbow_sum$TS2 - 2 / 12 * Valid_choices)
# mean(rainbow_sum$None)
# mean(rainbow_sum$None / Valid_choices)
# t.test(rainbow_sum$None - 2 / 12 * Valid_choices)
# Double_TS_choices = rainbow_sum$TS0and2 + rainbow_sum$TS1and2
# mean(Double_TS_choices)
# mean(Double_TS_choices / Valid_choices)
# t.test(Double_TS_choices - 2 / 12 * Valid_choices)
```
```{r Same for cloudy}
# cloudy_aliens = merge(subset(feed_aliens, phase == "2CloudySeason" & trial == 1, select = c("subjID", "sad_alien", "item_chosen")), all.x = T,
#                        all_ACCs)
# cloudy_aliens[order(cloudy_aliens$subjID, cloudy_aliens$sad_alien),]
# 
# cloudy_sum = ddply(cloudy_aliens, .(subjID), summarize,
#       TS0 = sum(ACC.only0, na.rm = T),
#       TS1 = sum(ACC.only1, na.rm = T),
#       TS2 = sum(ACC.only2, na.rm = T),
#       TS0and2 = sum(ACC.02, na.rm = T),
#       TS1and2 = sum(ACC.12, na.rm = T),
#       Missed = sum(ACC.Missed, na.rm = T),
#       None = sum(ACC.None, na.rm = T))
```
```{r Rainbow season - plot choice descriptives}
# # Combine OPTIMAL CHOICES with subject's choices in the rainbow season
# rainbow_aliens$TS = "rainbow"
# comb_dat = merge(correct_values,
#                  rainbow_aliens,
#                  by = c("subjID", "sad_alien", "TS", "item_chosen", "value_subj"), all = T)
# comb_dat
# 
# # Plot OPTIMAL CHOICES in every season together with subject's choices in the rainbow season
# comb_dat_sum = ddply(comb_dat,
#                      .(sad_alien, item_chosen, TS), summarize,
#                      value_subj = mean(value_subj, na.rm = T))
# 
# # Standardize TS values and rainbow choices to bring them into the same scale for plotting
# x = comb_dat_sum$value_subj[comb_dat_sum$TS != "rainbow"]
# mu = mean(x, na.rm = T)
# sd = sd(x, na.rm = T)
# comb_dat_sum$value_subj[comb_dat_sum$TS != "rainbow"] = (x - mu) / sd
# 
# x = comb_dat_sum$value_subj[comb_dat_sum$TS == "rainbow"]
# mu = mean(x, na.rm = T)
# sd = sd(x, na.rm = T)block-
# comb_dat_sum$value_subj[comb_dat_sum$TS == "rainbow"] = (x - mu) / sd
# 
# gg_rainbow_choice = ggplot(rainbow_aliens, aes(sad_alien, item_chosen, color = TS)) +#, size = value_subj
#   geom_point() +
#   theme(legend.position = "none") +
#   labs(x = "Alien", y = "", color = "") +
#   facet_grid( ~ paste("TS", TS))
# 
# gg_rainbow_choice_subj = gg_rainbow_choice
# gg_rainbow_choice_subj$data = rainbow_aliens
# gg_rainbow_choice_subj = gg_rainbow_choice_subj +
#   facet_wrap(~ paste("Subj", subjID))
# 
# if (gg_save) {
#   ggsave(file.path(plot_dir, "5gg_rainbow_choice.png"), gg_rainbow_choice, width = 7, height = 2)
#   ggsave(file.path(plot_dir, "5gg_rainbow_choice_subj2.png"), gg_rainbow_choice_subj, width = 15, height = 15)
# }
```
```{r Get mixed-block data and add values}
if (run_on == "humans") {
mixed_block = subset(all_files, block.type == "mixed")

# Add season-alien values (subj. and obj.)
all_values_perf_sub = subset(all_values_perf, phase == subj_value_phase & assess == "alien-same-season")
all_values_perf_sub$TS = substr(all_values_perf_sub$id, 2, 2)
all_values_perf_sub$sad_alien = substr(all_values_perf_sub$id, 1, 1)
all_values_perf_sub = subset(all_values_perf_sub, select = c("subjID", "TS", "sad_alien", "value_subj", "value_obj"))
colnames(all_values_perf_sub)[colnames(all_values_perf_sub) %in% c("value_subj", "value_obj")] = c("item_value_subj", "item_value_obj")

mixed_block = merge(mixed_block, all.x = T,
                    subset(all_values_perf_sub, select = c("subjID", "TS", "sad_alien", "item_value_subj", "item_value_obj")),
                    by = c("subjID", "sad_alien", "TS"))

# Add TS values (subj. and obj.)
all_values_perf_sub = subset(all_values_perf, phase == subj_value_phase & assess == "season")
colnames(all_values_perf_sub)[colnames(all_values_perf_sub) %in% c("id", "value_subj", "value_obj")] = c("TS", "TS_value_subj", "TS_value_obj")

mixed_block = merge(mixed_block, all.x = T,
                    subset(all_values_perf_sub, select = c("subjID", "TS", "TS_value_subj", "TS_value_obj")),
                    by = c("subjID", "TS"))

# Mark all trials with TS change only, alien change only, and change in both
mixed_block = mixed_block[order(mixed_block$subjID, mixed_block$trial_index),]
TS_switch = mixed_block$TS[1:nrow(mixed_block)-1] != mixed_block$TS[2:nrow(mixed_block)]
mixed_block$ts = c(NA, ifelse(TS_switch, "Switch", "Stay"))
alien_switch = mixed_block$sad_alien[1:nrow(mixed_block)-1] != mixed_block$sad_alien[2:nrow(mixed_block)]
mixed_block$alien = c(NA, ifelse(alien_switch, "Switch", "Stay"))
both_switch = mixed_block$ts == "Switch" & mixed_block$alien == "Switch"
both_stay = mixed_block$ts == "Stay" & mixed_block$alien == "Stay"
mixed_block$both = ifelse(both_switch, "Switch", ifelse(both_stay, "Stay", NA))
mixed_block$ts[mixed_block$both == "Switch"] = mixed_block$alien[mixed_block$both == "Switch"] = NA  # Remove trials from ts and aliens in which both switch

# Melt switch
mixed_block_l = melt(mixed_block, measure.vars = c("ts", "alien", "both"), variable.name = "level", value.name = "switch")
mixed_block_l$level = factor(mixed_block_l$level, levels = c("alien", "ts", "both"))
mixed_block_l_sum = ddply(subset(mixed_block_l, level == "ts" & !is.na(switch)), .(subjID, switch), summarize,
      n_trials = length(switch),
      ts_RT = median(rt, na.rm = T),
      ts_ACC = mean(ACC, na.rm = T))
mixed_block_l_sum_wide = reshape(mixed_block_l_sum, direction = "wide", timevar = "switch", idvar = c("subjID"))
mixed_block_l_sum_wide$RT_diff = with(mixed_block_l_sum_wide, ts_RT.Switch - ts_RT.Stay)
mixed_block_l_sum_wide$ACC_diff = with(mixed_block_l_sum_wide, ts_ACC.Switch - ts_ACC.Stay)

# Check everything looks good
mixed_block
subset(mixed_block, select = c("TS", "rt", "sad_alien", "ts", "alien", "both"))
mixed_block_l
mixed_block_l_sum_wide
}
```
```{r Mixed-block performance and RTs}
if (run_on == "humans") {
# Performance over time, dependent on (subj and obj) item values and TS values
gg_mixed_acc_TS_obj = ggplot(mixed_block, aes(alien_trial, 100 * ACC, color = TS_value_obj, group = TS_value_obj)) +  # it looks like there are just 7 blocks, but there shold be 7 * 3...
  stat_summary(fun.data = mean_se, geom = "pointrange") +
  stat_summary(fun.data = mean_se, geom = "line") +
  labs(x = "Block", y = "% correct", color = "TS value (obj.)")
gg_mixed_acc_TS_subj = gg_mixed_acc_TS_obj + aes(color = round(TS_value_subj), group = round(TS_value_subj)) + labs(color = "TS value (subj.)")
gg_mixed_acc_item_obj = gg_mixed_acc_TS_obj + aes(color = round(item_value_obj / 2 ) * 2, group = round(item_value_obj / 2) * 2) + labs(color = "Item value (obj.)")
gg_mixed_acc_item_subj = gg_mixed_acc_TS_obj + aes(color = round(item_value_subj / 2) * 2, group = round(item_value_subj / 2) * 2) + labs(color = "Item value (subj.)")

# RTs for changes in TS vs changes in alien
n_subj = length(unique(mixed_block$subjID))
ddply(mixed_block_l, .(level), summarize, n_trials_switch = sum(switch == "Switch", na.rm = T) / n_subj)
ddply(mixed_block_l, .(level), summarize, n_trials_stay = sum(switch == "Stay", na.rm = T) / n_subj)

gg_mixed_rts = ggplot(subset(mixed_block_l, !is.na(switch) & ACC == 1), aes(level, rt, color = level)) +
  stat_summary(fun.data = mean_se, geom = "pointrange", position = position_dodge(width = 0.9)) +
  labs(x = "", y = "RT (msec)", fill = "") +
  theme(legend.position = "none") +
  facet_grid(~ switch)
gg_mixed_ACCs = gg_mixed_rts + aes(y = 100 * ACC) + labs(y = "% correct")
gg_mixed_ACCs$data = subset(mixed_block_l, !is.na(switch))

gg_mixed_rts_within = ggplot(mixed_block_l_sum_wide, aes('', RT_diff, color = subjID)) +
  geom_violin() +
  stat_summary(fun.data = mean_se, geom = 'pointrange') +
  geom_dotplot(binaxis = "y", stackdir = "center", alpha = 0.3) +
  labs(x = "", y = "RT TS switch minus TS stay") +
  theme(legend.position = "none")
gg_mixed_ACCs_within = gg_mixed_rts_within + aes(y = ACC_diff) + labs(y = "ACC TS Switch minus ACC Stay")

if (gg_save) {
  ggsave(file.path(plot_dir, "6gg_mixed_acc_TS_obj.png"), gg_mixed_acc_TS_obj, width = 4, height = 3)
  ggsave(file.path(plot_dir, "6gg_mixed_acc_TS_subj.png"), gg_mixed_acc_TS_subj, width = 4, height = 3)
  ggsave(file.path(plot_dir, "6gg_mixed_acc_item_subj.png"), gg_mixed_acc_item_subj, width = 4, height = 3)
  ggsave(file.path(plot_dir, "6gg_mixed_acc_item_obj.png"), gg_mixed_acc_item_obj, width = 4, height = 3)
  ggsave(file.path(plot_dir, "6gg_mixed_rts.png"), gg_mixed_rts, width = 4, height = 3)
  ggsave(file.path(plot_dir, "6gg_mixed_ACCs.png"), gg_mixed_ACCs, width = 4, height = 3)
  ggsave(file.path(plot_dir, "6gg_mixed_rts_within.png"), gg_mixed_rts_within, width = 2, height = 3)
  ggsave(file.path(plot_dir, "6gg_mixed_ACCs_within.png"), gg_mixed_ACCs_within, width = 2, height = 3)
}
}
```

# Relationships between model parameters and behavior

```{r Get time to switch and compare to parameters (ACCfirst8_correct_dat)}
# Add roll_av_ACC to feed_aliens
n_trials = 8
feed_aliens$roll_av_ACC = rollmean(feed_aliens$ACC, n_trials, fill = NA, align = "right")
feed_aliens$roll_av_ACC[feed_aliens$alien_trial_sum <= n_trials / n_aliens] = NA  # the first n_trials trials (2 x 4 aliens) of each block need to be NA; otherwise they carry over between blocks / between subjects

# Check that it looks good
subset(feed_aliens, select = c("subjID", "sad_alien", "trial_index", "alien_trial", "alien_trial_sum", "TS", "ACC", "roll_av_ACC"))
ggplot(subset(feed_aliens, subjID == unique(all_files$subjID)[1] & trial_index < 500), aes(trial_index, roll_av_ACC, color = block %% 3)) +
  geom_point() +
  facet_grid(model_name ~ subjID)

# Create ACCfirst8_correct_dat
ACCfirst8_correct_dat = ddply(subset(feed_aliens, alien_trial_sum == (n_trials / n_aliens + 1)), .(subjID, phase, block), summarize,
                              roll_av_ACC = roll_av_ACC[1])
ACCfirst8_correct_dat = merge(parameter_dat, ACCfirst8_correct_dat, by = "subjID", all.y = T)
  
# Results: plot relationship between parameters and average trials to reach criterion
if (ACCfirst8_correct_dat$model_name[1] != "human") {
  gg_alpha_ACCfirst8 =
    ggplot(ACCfirst8_correct_dat, aes(alpha, roll_av_ACC, color = phase)) +
    geom_point(alpha = 0.5) +
    geom_smooth() +
    labs(y = "Switch speed (ACC in first 2 alien trials)") +
    facet_grid(model_name ~ .)
  gg_beta_ACCfirst8 = gg_alpha_ACCfirst8 + aes(x = beta)
  gg_forget_ACCfirst8 = gg_alpha_ACCfirst8 + aes(x = forget)
  gg_TSbias_ACCfirst8 = gg_alpha_ACCfirst8 + aes(x = create_TS_biased)
  
  if (gg_save) {
    ggsave(file.path(plot_dir, "/6gg_alpha_ACCfirst8.png"), gg_alpha_ACCfirst8, width = 4, height = 3 * length(unique(all_files$model_name)))
    ggsave(file.path(plot_dir, "/6gg_beta_ACCfirst8.png"), gg_beta_ACCfirst8, width = 4, height = 3 * length(unique(all_files$model_name)))
    ggsave(file.path(plot_dir, "/6gg_forget_ACCfirst8.png"), gg_forget_ACCfirst8, width = 4, height = 3 * length(unique(all_files$model_name)))
    ggsave(file.path(plot_dir, "/6gg_TSbias_ACCfirst8.png"), gg_TSbias_ACCfirst8, width = 4, height = 3 * length(unique(all_files$model_name)))
  }
}
gg_ACCfirst8 =
  ggplot(ACCfirst8_correct_dat, aes(phase, roll_av_ACC, fill = phase)) +
  geom_violin() +
  geom_point(position = "jitter", alpha = 0.1) +
  geom_boxplot(width = 0.1, size = 1) +
  labs(y = "Switch speed (ACC in first 2 alien trials)") +
  facet_grid(model_name ~ .)
ggsave(file.path(plot_dir, "/6gg_ACCfirst8.png"), gg_ACCfirst8, width = 4, height = 3 * length(unique(all_files$model_name)))
```
```{r Model parameters and pick aliens}
pick_aliens_avs_sub = subset(pick_aliens_avs, select = c("subjID", "model_name", "assess", "value_obj_diff", "av_ACC_diff", "selected_better_obj"), assess %in% c("alien-same-season", "season"))
pick_aliens_avs_long =
  melt(pick_aliens_avs_sub, id.vars = c("subjID", "model_name", "assess"), variable.name = "measure")
pick_aliens_avs_long = merge(pick_aliens_avs_long, parameter_dat, all.x = T)

gg_alpha_pickaliens = ggplot(pick_aliens_avs_long, aes(alpha, value, color = measure)) +
  geom_point() +
  geom_smooth() +
  facet_grid(model_name ~ assess)
gg_beta_pickaliens = gg_alpha_pickaliens + aes(x = beta)
gg_forget_pickaliens = gg_alpha_pickaliens + aes(x = forget)
gg_biasedTS_pickaliens = gg_alpha_pickaliens + aes(x = create_TS_biased)

if (gg_save) {
  ggsave(file.path(plot_dir, "/6gg_alpha_pickaliens.png"), gg_alpha_pickaliens, width = 10, height = 2 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "/6gg_beta_pickaliens.png"), gg_beta_pickaliens, width = 10, height = 2 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "/6gg_forget_pickaliens.png"), gg_forget_pickaliens, width = 10, height = 2 * length(unique(all_files$model_name)))
  ggsave(file.path(plot_dir, "/6gg_biasedTS_pickaliens.png"), gg_biasedTS_pickaliens, width = 10, height = 2 * length(unique(all_files$model_name)))
}
```
```{r Compare effects of TS and alien values (subjwise_regr_coefs)}
subjwise_regr_coefs = merge(subjwise_regr_coefs, parameter_dat, by = "subjID", all.x = T)
beta_limits = quantile(subjwise_regr_coefs$Estimate[subjwise_regr_coefs$predictor != "(Intercept)"], c(.1, .9), na.rm = T)
# sub_dat = subset(subjwise_regr_coefs, `Pr(>|z|)` < 0.05 | regr_model == "rainbow")
interesting_predictors =  c("item_value_obj", "TS_value_obj", "ACC_1back_self", "ACC_1back_others", "rew_1back_self")
models = unique(subjwise_regr_coefs$regr_model)

gg_values =
  ggplot(subset(subjwise_regr_coefs, predictor %in% interesting_predictors & Estimate > -1), aes(phase, Estimate, color = phase, alpha = `Pr(>|z|)` < 0.05)) +
  # geom_violin() +
  # geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 0.5)
  geom_hline(yintercept = 0, linetype = "dotted") +
  geom_point(position = "jitter") +
  stat_summary(fun.data = mean_se, geom = "pointrange", color = "black") +
  facet_grid(model_name ~ predictor)
ggsave(file.path(plot_dir, paste0("/6gg_values.png")), gg_values, width = 10, height = 3 * length(unique(all_files$model_name)))

if (length(models) > 1) {
  for (model in models) {
    gg_alpha_values =
      ggplot(subset(sub_dat, regr_model == model & predictor != "(Intercept)"), aes(alpha, Estimate, color = phase, group = phase)) +
      geom_point() +
      # geom_smooth(method = "lm") +
      geom_hline(yintercept = 0, linetype = "dotted") +
      facet_grid(model_name ~ predictor)
    gg_beta_values = gg_alpha_values + aes(x = beta)
    gg_TSbiased_values = gg_alpha_values + aes(x = create_TS_biased)
    gg_forget_values = gg_alpha_values + aes(x = forget)
  
    if (gg_save) {
      ggsave(file.path(plot_dir, paste0("/6gg_alpha_values_", model, ".png")), gg_alpha_values, width = 10, height = 3 * length(unique(all_files$model_name)))
      ggsave(file.path(plot_dir, paste0("/6gg_beta_values_", model, ".png")), gg_beta_values, width = 10, height = 3 * length(unique(all_files$model_name)))
      ggsave(file.path(plot_dir, paste0("/6gg_forget_values_", model, ".png")), gg_forget_values, width = 10, height = 3 * length(unique(all_files$model_name)))
      ggsave(file.path(plot_dir, paste0("/6gg_TSbiased_values_", model, ".png")), gg_TSbiased_values, width = 10, height = 3 * length(unique(all_files$model_name)))
    }
  }
}
```
```{r Plot glmer regression results}
if (run_regression) {
  gg_all_regr = ggplot(subset(all_regressions, predictor %in% interesting_predictors), aes(phase, Estimate, fill = predictor, alpha = `Pr(>|z|)` < 0.05)) +
    geom_bar(stat="identity", position = position_dodge(width = 0.9)) +
    facet_grid(model_name ~ regr_model)
  ggsave(file.path(plot_dir, "/6gg_all_regr.png"), gg_all_regr, width = 10, height = 2 * length(unique(all_files$model_name)))

  write.csv(all_regressions, paste(plot_dir, "/all_regressions.csv", sep = ""))
  write.csv(subjwise_regr_coefs, paste(plot_dir, "/subjwise_regr_coefs.csv", sep = ""))
}
```
```{r Start button}
```